### ISSUE TITLE
Keep getting this error

### ISSUE THREAD

**Issue by EricTheCarrot** [wipe2238/SteamDetour#3]
Despite copying and pasting the correct paths (I triple-check the spelling too) into the "advanced commands" in Steam, I keep getting this error. What am I doing wrong? 
![image](https://github.com/wipe2238/SteamDetour/assets/27117182/5ac55586-f489-42dd-868d-9335df27b13d)

**Comment by wipe2238** [comment]
Huh. I know you said you checked paths, but i have to ask...
Default location for FO2 on Steam is `Fallout 2`, while error message tries to find .exe in `Fallout2` directory. Did you made a copy of original directory? If not, that small missing space before `2` might be a problem here.

**Comment by EricTheCarrot** [comment]
> If not, that small missing space before `2` might be a problem here.
Yea, I checked the file path in Steam and it did not include the space when I copied it over which was strange. I guess somehow system error?
